### ISSUE TITLE
We should add some documentation

### ISSUE THREAD

**Issue by ChristopherKing42** [someguy867/Genetic-Fraction-Algorithm#3]
We should add comments and docstrings and documentation

**Comment by freeradical777** [comment]
I agree. Comments in the code would be nice too for visitors who don't know python super well

**Comment by ChristopherKing42** [comment]
Apparently you can only assign one person.

**Comment by ChristopherKing42** [comment]
Also, wiki should be good now.

**Comment by freeradical777** [comment]
I added information about the parameters for both simulations on the wiki.
