### ISSUE TITLE
We should add asexual reproduction to strings.py (read comment)

### ISSUE THREAD

**Issue by freeradical777** [someguy867/Genetic-Fraction-Algorithm#5]
My purpose with starting strings.py is to prove that sexual reproduction is generally more efficient when it is given the same parameters as asexual reproduction. Therefore, we should have it be like a race and see who generally finishes first!

**Comment by ChristopherKing42** [comment]
Closed in a820bcd86f6a0d3c798f62a5dd5b8ab176d9d9e1...22ab3bb2f8434cf7aa673a178ed031b3bb58850e
